services:
  worker-svd:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
